version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "18090:80"
      - "18095:443"
    volumes:
      - ./nginx/production.conf:/etc/nginx/nginx.conf:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      - app
    networks:
      - prod-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        labels: "service=nginx,env=production"

  app:
    image: ${DOCKER_REGISTRY:-}${DOCKER_IMAGE:-filename-generator}:${VERSION:-production-latest}
    # No external ports - only accessible via nginx
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${PRODUCTION_API_URL}
      # Production-specific environment variables
      LOG_LEVEL: ${LOG_LEVEL:-info}
      ENABLE_MONITORING: ${ENABLE_MONITORING:-true}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_ENVIRONMENT: production
      # Performance tuning
      NODE_OPTIONS: "--max-old-space-size=2048"
    restart: always
    networks:
      - prod-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
        labels: "service=filename-generator,env=production"


  redis:
    image: redis:7-alpine
    container_name: filename-generator-redis-prod
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    # No external ports - only accessible via internal network
    expose:
      - "6379"
    networks:
      - prod-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    volumes:
      - redis-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  prod-network:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 192.168.200.0/24

volumes:
  nginx-cache:
    driver: local
  redis-data:
    driver: local

